import Head from 'next/head'
import styles from '@styles/Home.module.scss'
import Link from 'next/link'

export default function Home({ handleCutoff, handleNoCutoff }: { handleCutoff: () => void, handleNoCutoff: () => void }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>

        <ul className={styles.menuOptions}>
          <li onMouseEnter={() => handleCutoff()} onMouseLeave={() => handleNoCutoff()}>music</li>
          <li onMouseEnter={() => handleCutoff()} onMouseLeave={() => handleNoCutoff()}> <Link href="/experiments">experiments</Link></li>
          <li onMouseEnter={() => handleCutoff()} onMouseLeave={() => handleNoCutoff()}>résumé</li>
        </ul>
      </main>
    </>
  )
}
